name: Application Deploying On AWS

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  VERSION: v1
  IMAGE: 514454346636.dkr.ecr.us-east-1.amazonaws.com/flaskapp-banking
  REGION: us-east-1
  S3_BUCKET: s3://514454346636-devops-scripts

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: Arvind1297/banking-app-2-tier
          ref: main

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::514454346636:role/github-action-deploy-role
          aws-region: ${{ env.REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.REGION }} | \
          docker login --username AWS --password-stdin \
          514454346636.dkr.ecr.${{ env.REGION }}.amazonaws.com
          echo "Login Successful to ECR ✅"

      - name: Upload Docker-Compose to S3
        run: |
          aws s3 mb ${{ env.S3_BUCKET }} --region ${{ env.REGION }} 2>/dev/null || true
          aws s3 cp docker-compose.yml ${{ env.S3_BUCKET }}/ --region ${{ env.REGION }}
          echo "Docker compose Uploaded ✅"